# Generated by Django 3.0 on 2022-04-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_management', '0006_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_at',
            field=models.DateField(null=True),
        ),
    ]
